# Site settings
theme: cluntop
title: 雨呢主页 # 你主页的标题
description: "雨呢主页, 雨呢导航" # 网站介绍

header-img: logo.png # 显示在首页的背景图片
email: clun@duck.com # Email
keyword: "雨呢主页, 雨呢导航" # 关键词
url: "https://cluntop.github.io" # 填写绝对 URL 地址
baseurl: "" # 例如，如果您的主页在“/pan”上托管
github_repo: "https://github.com/cluntop/cdn.git" # 您代码存储库
